name: CICD Rust
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    
    - name: install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: install
      run: make rs_install

    - name: lint
      run: make rs_lint

    - name: test
      run: make rs_test

    - name: format
      run: make rs_format